version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"